service: backend
frameworkVersion: '^4.6.2'
configValidationMode: error

provider:
  name: aws
  stage: dev
  region: us-east-1
  runtime: python3.13
  stackName: ${env:DEPLOY_APP}-${self:service}
  deploymentBucket:
    name: ${self:custom.s3.deploymentBucketName.${self:custom.stage}}
  apiGateway:
    apiKeys:
      - ${self:custom.servicePrefix}-key

package:
  individually: true
  patterns:
    - '!./**'

resources:
  - ${file(iam.yml)}

functions: ${file(functions.yml)}

layers: ${file(layers.yml)}

plugins:
  - serverless-deployment-bucket
  - '@serverless/safeguards-plugin'

custom:
  stage: ${opt:stage, self:provider.stage}
  safeguards:
    - safeguard: framework-version
      enforcementLevel: warning
      config: ${self:frameworkVersion}
    - safeguard: allowed-regions
      enforcementLevel: error
      config:
        - ${self:provider.region}
    - safeguard: allowed-function-names
      enforcementLevel: warning
      config: ${self:custom.servicePrefix}-${FUNCTION}
    - safeguard: no-wild-iam-role-statements
      enforcementLevel: warning
    - safeguard: allowed-stages
      enforcementLevel: error
      config:
        - dev
        - test
        - prod
  servicePrefix: ${env:DEPLOY_APP}-${self:service}
  developer: ${env:DEVELOPER}
  s3:
    deploymentBucketName:
      dev: ${self:provider.region}.cfn.${self:service}.${env:DEPLOY_APP}.${self:custom.stage}.${self:custom.developer}.deploys
      test: ${self:provider.region}.cfn.${self:service}.${env:DEPLOY_APP}.${self:custom.stage}.deploys
      prod: ${self:provider.region}.cfn.${self:service}.${env:DEPLOY_APP}.${self:custom.stage}.deploys
  rawReportsBucketName: ${ssm:/${env:DEPLOY_APP}-storage/RawReportsBucketName}
  rawReportsBucketArn: ${ssm:/${env:DEPLOY_APP}-storage/RawReportsBucketArn}
  accidentReportsQueueUrl: ${ssm:/${env:DEPLOY_APP}-queue/AccidentReportsQueueUrl}
  accidentReportsQueueArn: ${ssm:/${env:DEPLOY_APP}-queue/AccidentReportsQueueArn}
