[pytest]
addopts = -vvvv -rs --cov --cov-config=tests/.coveragerc --cov-report html --rootdir tests
env =
    MONGO_LOCAL_HOST=mongo
    MONGO_LOCAL_PORT=27017
    MONGO_LOCAL_DBNAME=trafficMonitoring
    MONGO_LOCAL_USERNAME=root
    MONGO_LOCAL_PASSWORD=example
    MONGO_CREDENTIALS_SECRET_NAME=/data-eng-course-secrets/MongoCredentials
    RAW_REPORTS_BUCKET_NAME=raw-reports-bucket-test
    PII_ENCRYPTION_KEY_SECRET_NAME=/data-eng-course-secrets/PiiEncryptionKey
    PII_ENCRYPTION_KEY=0ZXOOm8YKQwnGF1JrGOP6oh681L_56mC2CyGqtXm74A=
    POSTGRES_LOCAL_HOST=postgres
    POSTGRES_LOCAL_PORT=5432
    POSTGRES_LOCAL_DBNAME=traffic_monitoring
    POSTGRES_LOCAL_USERNAME=postgres
    POSTGRES_LOCAL_PASSWORD=example
    RDS_CREDENTIALS_SECRET_NAME=/data-eng-course-rds/MasterCredentials
    GENERATOR_BATCH_SIZE=5
    DEPLOY_APP=data-eng-course
    AWS_DEFAULT_REGION=us-east-1
filterwarnings =
    ignore::DeprecationWarning
