Resources:
  AccidentReportsQueueUrl:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/AccidentReportsQueueUrl
      Tier: Standard
      Type: String
      Value: !Ref AccidentReportsQueue

  AccidentReportsQueueArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/AccidentReportsQueueArn
      Tier: Standard
      Type: String
      Value: !GetAtt AccidentReportsQueue.Arn

  AccidentReportsDLQName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/AccidentReportsDLQName
      Tier: Standard
      Type: String
      Value: ${self:custom.queue.dlqName.${self:custom.stage}}

  AccidentReportsDLQUrl:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/AccidentReportsDLQUrl
      Tier: Standard
      Type: String
      Value: !Ref AccidentReportsDLQ

  AccidentReportsDLQArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/AccidentReportsDLQArn
      Tier: Standard
      Type: String
      Value: !GetAtt AccidentReportsDLQ.Arn
