Resources:
  AccidentReportsQueueUrl:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/AccidentReportsQueueUrl
      Tier: Standard
      Type: String
      Value: !Ref AccidentReportsQueue

  AccidentReportsQueueArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/AccidentReportsQueueArn
      Tier: Standard
      Type: String
      Value: !GetAtt AccidentReportsQueue.Arn

  AccidentReportsDLQName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/AccidentReportsDLQName
      Tier: Standard
      Type: String
      Value: ${self:custom.queue.accidentReports.dlqName.${self:custom.stage}}

  AccidentReportsDLQUrl:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/AccidentReportsDLQUrl
      Tier: Standard
      Type: String
      Value: !Ref AccidentReportsDLQ

  AccidentReportsDLQArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/AccidentReportsDLQArn
      Tier: Standard
      Type: String
      Value: !GetAtt AccidentReportsDLQ.Arn

  SensorReadingsQueueUrl:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/SensorReadingsQueueUrl
      Tier: Standard
      Type: String
      Value: !Ref SensorReadingsQueue

  SensorReadingsQueueArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/SensorReadingsQueueArn
      Tier: Standard
      Type: String
      Value: !GetAtt SensorReadingsQueue.Arn

  SensorReadingsDLQName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/SensorReadingsDLQName
      Tier: Standard
      Type: String
      Value: ${self:custom.queue.sensorReadings.dlqName.${self:custom.stage}}

  SensorReadingsDLQUrl:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/SensorReadingsDLQUrl
      Tier: Standard
      Type: String
      Value: !Ref SensorReadingsDLQ

  SensorReadingsDLQArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/SensorReadingsDLQArn
      Tier: Standard
      Type: String
      Value: !GetAtt SensorReadingsDLQ.Arn
