Resources:
  MongoCredentialsSecretArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/MongoCredentialsSecretArn
      Tier: Standard
      Type: String
      Value: !Ref MongoCredentialsSecret

  MongoCredentialsSecretName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/MongoCredentialsSecretName
      Tier: Standard
      Type: String
      Value: !Sub /${self:custom.servicePrefix}/MongoCredentials
