Resources:
  MongoCredentialsSecretArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/MongoCredentialsSecretArn
      Tier: Standard
      Type: String
      Value: !Ref MongoCredentialsSecret

  MongoCredentialsSecretName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/MongoCredentialsSecretName
      Tier: Standard
      Type: String
      Value: !Sub /${self:custom.servicePrefix}/MongoCredentials

  PiiEncryptionKeySecretArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/PiiEncryptionKeySecretArn
      Tier: Standard
      Type: String
      Value: !Ref PiiEncryptionKeySecret

  PiiEncryptionKeySecretName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/PiiEncryptionKeySecretName
      Tier: Standard
      Type: String
      Value: !Sub /${self:custom.servicePrefix}/PiiEncryptionKey
