Resources:
  AccidentReportsGeneratorRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:custom.servicePrefix}-AccidentReportsGenerator
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ${self:custom.servicePrefix}-AccidentReportsGenerator
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: sqs:SendMessage
                Resource: ${self:custom.sqs.accidentReportsExtractor.arn}
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: !Sub >-
                  arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${self:custom.secretsManager.mongoCredentials}-*

  AccidentReportsExtractorRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:custom.servicePrefix}-AccidentReportsExtractor
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ${self:custom.servicePrefix}-AccidentReportsExtractor
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: ${self:custom.sqs.accidentReportsExtractor.arn}
              - Effect: Allow
                Action: sqs:SendMessage
                Resource: ${self:custom.sqs.accidentReportsDispatcher.arn}
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: !Sub >-
                  arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${self:custom.secretsManager.mongoCredentials}-*

  AccidentReportsDispatcherRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:custom.servicePrefix}-AccidentReportsDispatcher
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ${self:custom.servicePrefix}-AccidentReportsDispatcher
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: ${self:custom.sqs.accidentReportsDispatcher.arn}
              - Effect: Allow
                Action: sns:Publish
                Resource: ${self:custom.sns.accidentReportsEtl.arn}

  AccidentReportsTransformerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:custom.servicePrefix}-AccidentReportsTransformer
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ${self:custom.servicePrefix}-AccidentReportsTransformer
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: ${self:custom.sqs.accidentReportsTransformer.arn}
              - Effect: Allow
                Action: sqs:SendMessage
                Resource: ${self:custom.sqs.accidentReportsTransformerDLQ.arn}
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: !Sub >-
                  arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${self:custom.secretsManager.rdsCredentials}-*

  SensorReadingsGeneratorRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:custom.servicePrefix}-SensorReadingsGenerator
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ${self:custom.servicePrefix}-SensorReadingsGenerator
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: sqs:SendMessage
                Resource: ${self:custom.sqs.sensorReadingsExtractor.arn}
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: !Sub >-
                  arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${self:custom.secretsManager.mongoCredentials}-*

  SensorReadingsExtractorRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:custom.servicePrefix}-SensorReadingsExtractor
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ${self:custom.servicePrefix}-SensorReadingsExtractor
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: ${self:custom.sqs.sensorReadingsExtractor.arn}
              - Effect: Allow
                Action: sqs:SendMessage
                Resource: ${self:custom.sqs.sensorReadingsDispatcher.arn}
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: !Sub >-
                  arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${self:custom.secretsManager.mongoCredentials}-*

  SensorReadingsDispatcherRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:custom.servicePrefix}-SensorReadingsDispatcher
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ${self:custom.servicePrefix}-SensorReadingsDispatcher
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: ${self:custom.sqs.sensorReadingsDispatcher.arn}
              - Effect: Allow
                Action: sns:Publish
                Resource: ${self:custom.sns.sensorReadingsEtl.arn}

  SensorReadingsTransformerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:custom.servicePrefix}-SensorReadingsTransformer
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ${self:custom.servicePrefix}-SensorReadingsTransformer
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: ${self:custom.sqs.sensorReadingsTransformer.arn}
              - Effect: Allow
                Action: sqs:SendMessage
                Resource: ${self:custom.sqs.sensorReadingsTransformerDLQ.arn}
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: !Sub >-
                  arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${self:custom.secretsManager.rdsCredentials}-*
