services:
  data-eng-course:
    container_name: 'DataEngCourse'
    build:
      context: .
      dockerfile: Dockerfile
      target: img-root
    volumes:
      - ..:/app
      - data-eng-course-bashhistory:/commandhistory
    working_dir: /app
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - sleep infinity

volumes:
  data-eng-course-bashhistory:
