services:
  data_eng_course_backend:
    container_name: 'DataEngCourseBackend'
    build:
      context: .
      dockerfile: ../../.docker/Dockerfile
      target: img-backend
    volumes:
      - ../..:/app
      - data-eng-course-backend-bashhistory:/commandhistory
    env_file:
      - ../../.envs/aws.env
      - ../../.envs/sls.env
      - ../.envs/config.env
    environment:
      - DEPLOY_APP=data-eng-course
    working_dir: /app/backend
    restart: unless-stopped
    depends_on:
      - mongo
    command:
      - /bin/sh
      - -c
      - sleep infinity

  mongo:
    container_name: 'DataEngCourseBackendMongo'
    image: mongo:7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    restart: unless-stopped

volumes:
  data-eng-course-backend-bashhistory:
