Resources:
  SiteUrl:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/SiteUrl
      Tier: Standard
      Type: String
      Value: !Sub https://${SiteDistribution.DomainName}
